version: '3'
services:
  db:
    image: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - usuarios-compose-network
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: usuario@123
      MYSQL_DATABASE: usuarios_db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    networks:
      - usuarios-compose-network
    links:
      - db
    ports:
      - 8000:80

  api:
    build: .
    container_name: usuarios-api
    networks:
      - usuarios-compose-network
    depends_on:
      - db
    ports:
      - 8080:8080
      - 5005:5005
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DEVTOOLS_RESTART_ENABLED: 'true'
      SPRING_DEVTOOLS_LIVERELOAD_ENABLED: 'true'
    # Executamos o spring-boot:run diretamente
    command: mvn spring-boot:run -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005" -Dspring-boot.run.profiles=dev

volumes:
  dbdata:

networks:
  usuarios-compose-network:
    driver: bridge