spring:
 datasource:
   url: jdbc:mysql://db:3306/usuarios_db?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
   username: root
   password: usuario@123

 jpa:
   hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
   hibernate.ddl-auto: update
   hibernate:
     jdbc: time_zone = TimeZone
   show-sql: true
   properties:
     hibernate:
       format_sql: true

 jackson:
   default-property-inclusion: NON_NULL

 devtools:
   restart:
     enabled: true
     poll-interval: 2s
     quiet-period: 1s
   livereload:
     enabled: true
   add-properties: true

jwt:
 secret: _M@d50n@r@uj0d@51lv@_
 expiration: 30

server:
 error:
   include-message: always
   include-stacktrace: always
   include-binding-errors: always

logging:
 level:
   org.springframework.web: INFO
   org.hibernate.SQL: DEBUG
   org.hibernate.type.descriptor.sql.BasicBinder: TRACE
   root: INFO
